# Generated by Django 2.1.7 on 2019-03-28 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0003_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('rid', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('summary', models.TextField(null=True)),
                ('pros', models.TextField(null=True)),
                ('cons', models.TextField(null=True)),
                ('advices_to_management', models.TextField(null=True)),
                ('overall_ratings', models.CharField(max_length=10)),
                ('work_balance_stars', models.CharField(max_length=10)),
                ('culture_values_stars', models.CharField(max_length=10)),
                ('career_opportunities_stars', models.CharField(max_length=10)),
                ('company_benefit_stars', models.CharField(max_length=10)),
                ('senior_management_stars', models.CharField(max_length=10)),
                ('helpful_count', models.IntegerField()),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basic_app.Company')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basic_app.Position')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basic_app.UserProfileInfo')),
            ],
        ),
    ]
