# Generated by Django 2.1.7 on 2019-03-28 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0005_deleteid'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.IntegerField()),
                ('summary', models.TextField(null=True)),
            ],
        ),
    ]
