# Generated by Django 2.1.7 on 2019-03-28 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0009_addid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addid',
            name='this_cid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='addid',
            name='this_pid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='addid',
            name='this_uid',
            field=models.IntegerField(),
        ),
    ]
