# Generated by Django 2.1.7 on 2019-03-28 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0010_auto_20190328_2205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addid',
            old_name='this_rid',
            new_name='cid',
        ),
        migrations.RemoveField(
            model_name='addid',
            name='this_advices_to_management',
        ),
        migrations.RemoveField(
            model_name='addid',
            name='this_career_opportunities_stars',
        ),
        migrations.RemoveField(
            model_name='addid',
            name='this_cid',
        ),
        migrations.RemoveField(
            model_name='addid',
            name='this_company_benefit_stars',
        ),
        migrations.RemoveField(
            model_name='addid',
            name='this_cons',
        ),
        migrations.RemoveField(
            model_name='addid',
            name='this_culture_values_stars',
        ),
        migrations.RemoveField(
            model_name='addid',
            name='this_date',
        ),
        migrations.RemoveField(
            model_name='addid',
            name='this_helpful_count',
        ),
        migrations.RemoveField(
            model_name='addid',
            name='this_overall_ratings',
        ),
        migrations.RemoveField(
            model_name='addid',
            name='this_pid',
        ),
        migrations.RemoveField(
            model_name='addid',
            name='this_pros',
        ),
        migrations.RemoveField(
            model_name='addid',
            name='this_senior_management_stars',
        ),
        migrations.RemoveField(
            model_name='addid',
            name='this_summary',
        ),
        migrations.RemoveField(
            model_name='addid',
            name='this_uid',
        ),
        migrations.RemoveField(
            model_name='addid',
            name='this_work_balance_stars',
        ),
        migrations.AddField(
            model_name='addid',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='addid',
            name='country',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='addid',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='addid',
            name='state',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
